version: '3.8'

services:
  # Frontend service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://server:5000/api
      - VITE_GEMINI_API_KEY=${GEMINI_API_KEY}
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - server

  # Backend service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped